// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADQ1c9cGzd1MxtQgml6nNO_vCrjLtkjk0',
    appId: '1:16437638871:web:cb0cc62178b686cb702292',
    messagingSenderId: '16437638871',
    projectId: 'chatapp-e34d0',
    authDomain: 'chatapp-e34d0.firebaseapp.com',
    storageBucket: 'chatapp-e34d0.appspot.com',
    measurementId: 'G-VGF10EV7VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB31Mcq7ruwnIzAR67sqdIJMMgmhQiMtZo',
    appId: '1:16437638871:android:993b56246140aa6d702292',
    messagingSenderId: '16437638871',
    projectId: 'chatapp-e34d0',
    storageBucket: 'chatapp-e34d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG48x0tT6wxY8tCqMx4Rcs0LzIe01EfTg',
    appId: '1:16437638871:ios:3615b5f380f401a3702292',
    messagingSenderId: '16437638871',
    projectId: 'chatapp-e34d0',
    storageBucket: 'chatapp-e34d0.appspot.com',
    iosClientId:
        '16437638871-8qe786uboa5q04fracnrbu1tt5ahha61.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG48x0tT6wxY8tCqMx4Rcs0LzIe01EfTg',
    appId: '1:16437638871:ios:b3cc3d7981b0e000702292',
    messagingSenderId: '16437638871',
    projectId: 'chatapp-e34d0',
    storageBucket: 'chatapp-e34d0.appspot.com',
    iosClientId:
        '16437638871-k45t91d1po3ms22lffcpl6qur2gelolh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
